 meta_product_name: "My Digital Cookbook"
 meta_title: "My Digital Cookbook - Un lieu unique et facile d'accès pour stocker des photos de recettes et vos recettes en ligne"
 meta_description: "Une application web pour avoir sous la main dans un seul endroit toutes les recettes que vous glanez sur le web, sur les reseaux sociaux, ou dans des livres, en format photo ou via leur url. "
 meta_image: "digital-cookbook-image.jpg"
  